name: Python application

on:
  schedule:
    - cron: '36 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Collect and notify about outdated packages
      env:
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      run: |
        set +x
        PACKAGES=$(pip list --outdated)
        PAYLOAD=$(jq --arg packages "$PACKAGES" '{text: ("```" + $packages + "```")}' -n)
        curl -X POST "$SLACK_WEBHOOK" -d "payload=$PAYLOAD"
